Package dependencies
tipoff/laravel-google-api pull request #40
Opened 2021-04-25 17:38 UTC by huntermontell

2021-05-01 19:44 UTC, joshtorres requested changes
Please fix tests

2021-05-01 20:56 UTC, wolfrednicolas commented
@huntermontell looks like https://github.com/spatie/data-transfer-object needs `php 8` for version `3.x`, but the prefer-lowest test is in php `7.4.16`

2021-05-01 21:18 UTC, wolfrednicolas commented
@huntermontell 
also the class `FlexibleDataTransferObject` does not exist for the newest version

https://github.com/spatie/data-transfer-object/tree/master/src

but for the v2 it does

https://github.com/spatie/data-transfer-object/tree/v2/src

so here you have a conflict between the versions and the PHP

multiples solutions here

1- upgrading everthing here to php 8, remove the `"php": "^7.4|^8.0"` to `"php": "^8.0"` in the `composer.json`  .... also remove the lowest version in the test
2- other approach would be downgrade the `spatie/data-transfer-object` to `2.x`

it's a tough ..... ask to the team what will be the best approach

2021-05-04 04:41 UTC, joshtorres commented
@phuclh do you have any input on this since you worked on it?

2021-05-04 05:02 UTC, phuclh reviewed
@joshtorres I left the review

2021-05-04 05:02 UTC, phuclh commented on composer.json
> +        "spatie/data-transfer-object": "^3.1",
We can only use v2 at this time. The v3 only supports PHP8

2021-05-05 19:14 UTC, joshtorres commented
Ok let's downgrade to v2

2021-05-06 23:54 UTC, wolfrednicolas commented
Ready to merge @joshtorres

2021-05-06 23:57 UTC, joshtorres approved these changes
Thank you!

2021-05-06 23:57 UTC, merged